.gitignore, index.js, package.json
add initial setup and configure mongodb
=> add initial setup files

frontend/src/App.css, frontend/src/components/session/login.css, frontend/src/components/session/login_form.js, frontend/src/components/session/signup.css, frontend/src/components/session/signup_form.js
Added some basic css for the login and signup forms
=> Loginsignupcss

frontend/src/components/App.js, frontend/src/components/session/login_form.js, frontend/src/components/splash/splash.jsx, frontend/src/reducers/session_reducer.js, frontend/src/util/route_util.js
=> login in fix & get lat lngs on splash

app.js, models/SurfSession.js, routes/api/spots.js
Misnomer - this is actually surf spot routes
=> Surf spot validations

app.js
had leftover code from twitter tutorial that was generating user on every get request to home page
=> fix issue on get request to "/"

models/Favorite.js, routes/api/spots.js, routes/api/users.js
Add:
-GET /api/users/:id/favorites 
-GET /api/spots/:id/favorites
-POST /api/spots/:id/favorites
=> add favorites routes

frontend/public/index.html
Re-added key into index script
=> Index html

frontend/src/components/App.js, frontend/src/components/surfspots/surf_spot.js, frontend/src/components/surfspots/surf_spot_container.js, frontend/src/components/surfspots/surfspot.css
=> Better surf form

frontend/src/actions/surf_session_actions.js, frontend/src/reducers/entities_reducer.js, frontend/src/reducers/surf_session_reducer.js, frontend/src/util/surf_session_api_util.js
Surf session api util, actions, and reducer
=> Surf session actions

frontend/src/components/session/login_form.js
add preventDefault to demo user login
=> fix issue with flashing errors for demo user

frontend/src/components/App.js, frontend/src/components/surf_session/surf_session_index.jsx, frontend/src/components/surf_session/surf_session_item.jsx, frontend/src/index.js, frontend/src/store/store.js
Made the delete buttons for surf sessions actually work
=> Surf sessions

frontend/src/components/App.js, frontend/src/components/maps/spot_index.css, frontend/src/components/maps/spot_index.jsx, frontend/src/components/maps/spot_index_container.js, frontend/src/components/surf_session/surf_session_index.jsx, frontend/src/components/surfspots/spot_show.js
created basic surfspot index, some css
=> surfspot index

frontend/src/components/reset.css, frontend/src/components/surfspots/spot_show.js, frontend/src/components/surfspots/surf_spot.js, package.json
add header to surf spot page, capitalize title using lodash
=> Add headers to pages

frontend/src/components/footer/footer.jsx
make it so about us links open in new tab
=> Double render

frontend/src/components/maps/spot_index.jsx, frontend/src/components/surfspots/spot_show.js, frontend/src/store/store.js
fixed incorrect review rendering, deleted spots not rendering on list after delete
=> review fixy

frontend/src/components/App.css, frontend/src/components/App.js, frontend/src/components/footer/footer.css, frontend/src/components/surfspots/surfspot.css
fixed background img, navbar, review form addition(s)
=> css fixing

frontend/src/components/App.css, frontend/src/components/footer/footer.css
set bckground img height to 100%
=> bckground height

frontend/src/components/maps/spot_index.css, frontend/src/components/maps/spot_index.jsx, frontend/src/components/surf_session/surf_session_container.js, frontend/src/components/surf_session/surf_session_form.jsx, frontend/src/components/surf_session/surf_session_index.jsx, frontend/src/components/surf_session/surf_session_index_container.js, frontend/src/components/surf_session/surf_session_item.jsx, frontend/src/components/surfspots/spot_show.js, frontend/src/components/surfspots/spot_show_container.js, frontend/src/components/surfspots/surfspot.css, frontend/src/store/store.js
fixed inf loop update on profile, added some directions, able to delete reviews, minor css fixes
=> Feb improv

frontend/public/index.html, frontend/src/components/surfspots/surf_spot.js, frontend/src/components/surfspots/surfspot.css
added search box on create surf spot page
=> searchbox functionality

frontend/src/components/App.js, frontend/src/components/splash/splash.jsx, frontend/src/index.js, frontend/src/util/route_util.js
=> comment out line
